// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbsemantic

type Expression = byte

const (
	ExpressionNONE                   Expression = 0
	ExpressionStringExpression       Expression = 1
	ExpressionArrayExpression        Expression = 2
	ExpressionFunctionExpression     Expression = 3
	ExpressionBinaryExpression       Expression = 4
	ExpressionCallExpression         Expression = 5
	ExpressionConditionalExpression  Expression = 6
	ExpressionIdentifier             Expression = 7
	ExpressionIdentifierExpression   Expression = 8
	ExpressionLogicalExpression      Expression = 9
	ExpressionMemberExpression       Expression = 10
	ExpressionIndexExpression        Expression = 11
	ExpressionObjectExpression       Expression = 12
	ExpressionUnaryExpression        Expression = 13
	ExpressionBooleanLiteral         Expression = 14
	ExpressionDateTimeLiteral        Expression = 15
	ExpressionDurationLiteral        Expression = 16
	ExpressionFloatLiteral           Expression = 17
	ExpressionIntegerLiteral         Expression = 18
	ExpressionStringLiteral          Expression = 19
	ExpressionRegexpLiteral          Expression = 20
	ExpressionUnsignedIntegerLiteral Expression = 21
)

var EnumNamesExpression = map[Expression]string{
	ExpressionNONE:                   "NONE",
	ExpressionStringExpression:       "StringExpression",
	ExpressionArrayExpression:        "ArrayExpression",
	ExpressionFunctionExpression:     "FunctionExpression",
	ExpressionBinaryExpression:       "BinaryExpression",
	ExpressionCallExpression:         "CallExpression",
	ExpressionConditionalExpression:  "ConditionalExpression",
	ExpressionIdentifier:             "Identifier",
	ExpressionIdentifierExpression:   "IdentifierExpression",
	ExpressionLogicalExpression:      "LogicalExpression",
	ExpressionMemberExpression:       "MemberExpression",
	ExpressionIndexExpression:        "IndexExpression",
	ExpressionObjectExpression:       "ObjectExpression",
	ExpressionUnaryExpression:        "UnaryExpression",
	ExpressionBooleanLiteral:         "BooleanLiteral",
	ExpressionDateTimeLiteral:        "DateTimeLiteral",
	ExpressionDurationLiteral:        "DurationLiteral",
	ExpressionFloatLiteral:           "FloatLiteral",
	ExpressionIntegerLiteral:         "IntegerLiteral",
	ExpressionStringLiteral:          "StringLiteral",
	ExpressionRegexpLiteral:          "RegexpLiteral",
	ExpressionUnsignedIntegerLiteral: "UnsignedIntegerLiteral",
}
